# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-01-09 17:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_comment_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='title',
            field=models.CharField(default=None, max_length=1024),
            preserve_default=False,
        ),
    ]
